# Maria DB PVCs

# Maria DB Config PVCs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-config-pvc
  namespace: media-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
---