# Monitoring Helm Values for Prometheus Stack

defaultRules:
  rules:
    etcd: false
    kubeScheduler: false
    kubeControllerManager: false
    kubeProxy: false

grafana:
  admin:
    existingSecret: monitoring-secrets
    userKey: grafana-admin-user
    passwordKey: grafana-admin-password
  persistence:
    enabled: true
    storageClassName: longhorn
    size: 2Gi
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.local
    path: /

prometheus:
  prometheusSpec:
    retention: 5d
    retentionSize: "5GiB"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 7Gi

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: [ "ReadWriteOnce" ]
          resources:
            requests:
              storage: 2Gi

kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
