# CTFd Storage

# CTFd Database PVC
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctfd-db-config-pvc
  namespace: ctfd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
---

# CTFd Logs PVC
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctfd-logs-pvc
  namespace: ctfd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
---

# CTFd Uploads PVC
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ctfd-uploads-pvc
  namespace: ctfd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: longhorn
---